```{r}
library(ggplot2)
data(diamonds)
summary(diamonds)
```

Price histogram by cut
```{r}
ggplot(diamonds, aes(x = price)) +
  geom_histogram() +
  facet_wrap(~cut)
```

summary by cut
```{r}
by(diamonds$price, diamonds$cut, summary)
```

```{r}
?diamonds
```

```{r}
ggplot(diamonds, aes(x = price)) +
  geom_histogram() +
  facet_wrap(~cut, scales = "free_y")
```
# Create a histogram of price per carat and facet it by cut. adjust the bin width and transform the scale of the x-axis using log10
```{r}
ggplot(diamonds, aes(x = price/carat)) +
  geom_histogram() +
  facet_wrap(~cut, scales = "free_y") +
  scale_x_log10()
```

Using box plots
```{r}
ggplot(diamonds, aes(x = cut, y = price)) +
  geom_boxplot()
```

```{r}
ggplot(diamonds, aes(x = clarity, y = price)) +
  geom_boxplot()
```

```{r}
ggplot(diamonds, aes(x = color, y = price)) +
  geom_boxplot()

by(diamonds$price, diamonds$color, summary)
```

```{r}
IQR(subset(diamonds, color == "D")$price)
IQR(subset(diamonds, color == "J")$price)
```

price per acrat of diamonds by colors using boxplot
```{r}
ggplot(diamonds, aes(x = color, y = price/carat)) +
  geom_boxplot()
```

carat using a frequency polygon

```{r}
ggplot(subset(diamonds, diamonds$carat < 2), aes(x = carat)) +
  geom_freqpoly(show.legend = TRUE) +
  stat_bin(aes(y = ..count.., label = ..count..), geom="text", vjust=-.1) + scale_x_continuous(breaks = seq(0,5,0.1))


```

```{r}
qplot(x=carat, data = diamonds, geom = "freqpoly", ylim = c(2000,15000)) +
  scale_x_continuous(breaks = seq(0,5,0.1)) +
  coord_cartesian(xlim = c(0,2))
```

```{r}
?geom_freqpoly
```

